export const SHOW_PRODUCTS = 'SHOW_PRODUCTS';
export const SHOW_PRODUCTS_SUCCESS = 'SHOW_PRODUCTS_SUCCESS';
export const SHOW_PRODUCTS_FAILURE = 'SHOW_PRODUCTS_FAILURE';

export const SHOW_PRODUCT = 'SHOW_PRODUCT';
export const SHOW_PRODUCT_SUCCESS = 'SHOW_PRODUCT_SUCCESS';
export const SHOW_PRODUCT_FAILURE = 'SHOW_PRODUCT_FAILURE';

export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const EDIT_PRODUCT = 'EDIT_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';

// Filter types

export const SORT_BY = 'SORT_BY';



